Feat playwright api
OpalinskyiSerhii98/AQA-playwright pull request #6
Opened 2024-04-16 21:16 UTC by OpalinskyiSerhii98

2024-04-17 09:56 UTC, sttaran requested changes

2024-04-17 09:56 UTC, sttaran commented on src/components/Body.js
> +}
You should associate your components with components on a page but not with HTML

2024-04-17 09:56 UTC, sttaran commented on src/components/Body.js
> +}
I do not think you need it

2024-04-17 09:56 UTC, sttaran commented on tests/garage/garage.spec.js
> +        await page.locator('.modal-content  .btn-primary').click()
use POM

2024-04-18 19:12 UTC, sttaran requested changes

2024-04-18 19:12 UTC, sttaran commented on tests/garage/profile.spec.js
> +        await page.goto('/panel/profile')
you should check that mocked value is displayed on UI

2024-04-20 07:15 UTC, sttaran requested changes

2024-04-20 07:15 UTC, sttaran commented on tests/garage/profile.spec.js
> +        const profileName = await page.$eval('.profile_name', (element) => element.textContent.trim());
use https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text

and use POM

2024-04-20 12:15 UTC, sttaran requested changes

2024-04-20 12:15 UTC, sttaran commented on tests/garage/profile.spec.js
> +        const name = "John Doe"
create name based on PROFILE_MOCK_RESPONSE

2024-04-20 12:15 UTC, sttaran requested changes

2024-04-20 12:15 UTC, sttaran commented on tests/garage/profile.spec.js
> +        const profileName = page.locator('.profile_name')
use POM

2024-04-20 12:38 UTC, OpalinskyiSerhii98 commented on tests/garage/profile.spec.js
> +        const name = "John Doe"
done

2024-04-22 16:14 UTC, merged